<?php
$title = 'Adicionar nova turma';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$form = $this->form;
$form->setAttribute('action', 'add');
$form->prepare();
$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
?>

<div class="form_element">
<?php
echo $this->formRow($form->get('name'), null, true);
?>
</div>

<?php
echo $this->formRow($form->get('academic_year'), null, true);
?>

<?php
echo $this->formRow($form->get('terms'), null, true);
?>

<?php
echo $this->formRow($form->get('teacher'), null, true);
?>

<?php
echo $this->formSubmit($form->get('submit'));
?>

<?php
echo $this->form()->closeTag();
?>