<?php
$title = "Boletim";

$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<table border="1">
<tr>
<td>Disciplinas</td>

<?php 
//Imprime colunas das notas (varia conforme a organização da escola)
for ($i = 0; $i < $terms; $i++) {
    echo "<td>".$i."</td>";
} 
?>

<td>Média</td>
</tr>

<?php 
// Imprime as notas
$j=0; 
foreach ($grades as $g) {
    echo "<tr>";
    echo "<td>".$this->escapehtml(array_keys($grades)[$j])."</td>";
    $j++;
    $avg = 0;
    for ($i = 1; $i <= $terms; $i++) {
        echo "<td>";
            if (array_key_exists($i, $g)) { 
                echo $g[$i]; 
                $avg += $g[$i];
            }
        echo "</td>";
    }
    echo "<td>".number_format($avg / $terms, 2)."</td>";
    echo "</tr>";
}
?>
</table>